import type { Guest, GuestStats } from "@/types/guest";

export const mockGuests: Guest[] = [
  {
    id: "gst_001",
    fullName: "Kwame Mensah",
    phone: "+233 24 123 4567",
    email: "kwame.mensah@email.com",
    nationality: "Ghanaian",
    idType: "national_id",
    idNumber: "GHA-123456789-0",
    address: "12 Independence Ave, Accra",
    guestStatus: "reserved",
    totalVisits: 4,
    totalSpent: 4850,
    vipStatus: true,
    notes: ["Prefers upper floors", "Returning guest"],
  },
  {
    id: "gst_002",
    fullName: "Ama Osei",
    phone: "+233 55 987 6543",
    email: "ama.osei@email.com",
    nationality: "Ghanaian",
    idType: "national_id",
    idNumber: "GHA-987654321-1",
    address: "45 Ring Road Central, Kumasi",
    guestStatus: "in_house",
    totalVisits: 2,
    totalSpent: 1200,
    vipStatus: false,
    notes: ["Late check-out approved"],
  },
  {
    id: "gst_003",
    fullName: "James Okonkwo",
    phone: "+234 803 456 7890",
    email: "j.okonkwo@corp.com",
    nationality: "Nigerian",
    idType: "passport",
    idNumber: "A12345678",
    address: "Victoria Island, Lagos",
    guestStatus: "reserved",
    totalVisits: 1,
    totalSpent: 0,
    vipStatus: false,
    notes: ["Requires airport pickup"],
  },
  {
    id: "gst_004",
    fullName: "Priya Sharma",
    phone: "+91 98 7654 3210",
    email: "priya.sharma@travel.in",
    nationality: "Indian",
    idType: "passport",
    idNumber: "Z9876543",
    address: "Mumbai, Maharashtra",
    guestStatus: "reserved",
    totalVisits: 3,
    totalSpent: 6200,
    vipStatus: true,
    notes: ["Returning guest", "Vegetarian meals"],
  },
  {
    id: "gst_005",
    fullName: "Michael Chen",
    phone: "+1 415 555 0198",
    email: "mchen@business.com",
    nationality: "American",
    idType: "passport",
    idNumber: "US8829103",
    address: "San Francisco, CA",
    guestStatus: "checked_out",
    totalVisits: 5,
    totalSpent: 12400,
    vipStatus: true,
    notes: ["Corporate account", "Prefers quiet rooms"],
  },
  {
    id: "gst_006",
    fullName: "Elena Vasquez",
    phone: "+34 612 345 678",
    email: "elena.v@email.es",
    nationality: "Spanish",
    idType: "passport",
    idNumber: "ESP445566",
    address: "Barcelona, Spain",
    guestStatus: "reserved",
    totalVisits: 1,
    totalSpent: 0,
    vipStatus: false,
    notes: [],
  },
  {
    id: "gst_007",
    fullName: "David Thompson",
    phone: "+44 7700 900123",
    email: "d.thompson@uk.co",
    nationality: "British",
    idType: "passport",
    idNumber: "GB11223344",
    address: "London, UK",
    guestStatus: "checked_out",
    totalVisits: 2,
    totalSpent: 2100,
    vipStatus: false,
    notes: [],
  },
  {
    id: "gst_008",
    fullName: "Fatima Al-Rashid",
    phone: "+971 50 123 4567",
    email: "fatima.ar@email.ae",
    nationality: "Emirati",
    idType: "passport",
    idNumber: "AE998877",
    address: "Dubai, UAE",
    guestStatus: "reserved",
    totalVisits: 2,
    totalSpent: 5400,
    vipStatus: true,
    notes: ["Halal dining preference"],
  },
  {
    id: "gst_009",
    fullName: "Robert Kim",
    phone: "+82 10 9876 5432",
    email: "rkim@email.kr",
    nationality: "South Korean",
    idType: "passport",
    idNumber: "KR556677",
    address: "Seoul, South Korea",
    guestStatus: "checked_out",
    totalVisits: 1,
    totalSpent: 450,
    vipStatus: false,
    notes: [],
  },
  {
    id: "gst_010",
    fullName: "Sarah Mitchell",
    phone: "+233 20 555 1234",
    email: "sarah.m@email.com",
    nationality: "Ghanaian",
    idType: "national_id",
    idNumber: "GHA-445566778-2",
    address: "East Legon, Accra",
    guestStatus: "reserved",
    totalVisits: 3,
    totalSpent: 2800,
    vipStatus: false,
    notes: ["Returning guest"],
  },
  {
    id: "gst_011",
    fullName: "Thomas Berg",
    phone: "+49 170 1234567",
    email: "t.berg@email.de",
    nationality: "German",
    idType: "passport",
    idNumber: "DE778899",
    address: "Berlin, Germany",
    guestStatus: "in_house",
    totalVisits: 1,
    totalSpent: 1552,
    vipStatus: false,
    notes: [],
  },
  {
    id: "gst_012",
    fullName: "Grace Adjei",
    phone: "+233 27 888 9999",
    email: "grace.adjei@email.com",
    nationality: "Ghanaian",
    idType: "national_id",
    idNumber: "GHA-334455667-3",
    address: "Tema, Greater Accra",
    guestStatus: "reserved",
    totalVisits: 1,
    totalSpent: 0,
    vipStatus: false,
    notes: ["Family with children"],
  },
  {
    id: "gst_013",
    fullName: "Kofi Asante",
    phone: "+233 26 111 2233",
    email: "kofi.asante@email.com",
    nationality: "Ghanaian",
    idType: "national_id",
    idNumber: "GHA-112233445-4",
    address: "Cantonments, Accra",
    guestStatus: "in_house",
    totalVisits: 6,
    totalSpent: 8900,
    vipStatus: true,
    notes: ["VIP lounge access", "Returning guest"],
  },
  {
    id: "gst_014",
    fullName: "Abena Darko",
    phone: "+233 24 444 5566",
    email: "abena.darko@email.com",
    nationality: "Ghanaian",
    idType: "national_id",
    idNumber: "GHA-556677889-5",
    address: "Osu, Accra",
    guestStatus: "checked_out",
    totalVisits: 2,
    totalSpent: 1750,
    vipStatus: false,
    notes: [],
  },
  {
    id: "gst_015",
    fullName: "Yaw Boateng",
    phone: "+233 55 333 2211",
    email: "yaw.boateng@email.com",
    nationality: "Ghanaian",
    idType: "drivers_license",
    idNumber: "DL-ACC-998877",
    address: "Takoradi, Western Region",
    guestStatus: "reserved",
    totalVisits: 1,
    totalSpent: 0,
    vipStatus: false,
    notes: ["Conference attendee"],
  },
  {
    id: "gst_016",
    fullName: "Sophie Laurent",
    phone: "+33 6 12 34 56 78",
    email: "sophie.l@email.fr",
    nationality: "French",
    idType: "passport",
    idNumber: "FR334455",
    address: "Paris, France",
    guestStatus: "in_house",
    totalVisits: 2,
    totalSpent: 3200,
    vipStatus: false,
    notes: ["Prefers French press coffee"],
  },
  {
    id: "gst_017",
    fullName: "Hiroshi Tanaka",
    phone: "+81 90 1234 5678",
    email: "hiroshi.t@email.jp",
    nationality: "Japanese",
    idType: "passport",
    idNumber: "JP887766",
    address: "Tokyo, Japan",
    guestStatus: "checked_out",
    totalVisits: 1,
    totalSpent: 2100,
    vipStatus: false,
    notes: [],
  },
  {
    id: "gst_018",
    fullName: "Nana Akua",
    phone: "+233 20 777 8899",
    email: "nana.akua@email.com",
    nationality: "Ghanaian",
    idType: "national_id",
    idNumber: "GHA-667788990-6",
    address: "Kumasi, Ashanti Region",
    guestStatus: "in_house",
    totalVisits: 4,
    totalSpent: 4100,
    vipStatus: true,
    notes: ["Wedding party coordinator", "Returning guest"],
  },
  {
    id: "gst_019",
    fullName: "Marcus Williams",
    phone: "+1 212 555 0142",
    email: "marcus.w@email.com",
    nationality: "American",
    idType: "passport",
    idNumber: "US3344556",
    address: "New York, NY",
    guestStatus: "reserved",
    totalVisits: 1,
    totalSpent: 0,
    vipStatus: false,
    notes: [],
  },
  {
    id: "gst_020",
    fullName: "Chioma Eze",
    phone: "+234 701 234 5678",
    email: "chioma.eze@email.com",
    nationality: "Nigerian",
    idType: "national_id",
    idNumber: "NG-88776655",
    address: "Abuja, Nigeria",
    guestStatus: "checked_out",
    totalVisits: 3,
    totalSpent: 3600,
    vipStatus: false,
    notes: ["Returning guest"],
  },
  {
    id: "gst_021",
    fullName: "Lars Johansson",
    phone: "+46 70 123 4567",
    email: "lars.j@email.se",
    nationality: "Swedish",
    idType: "passport",
    idNumber: "SE112233",
    address: "Stockholm, Sweden",
    guestStatus: "in_house",
    totalVisits: 1,
    totalSpent: 980,
    vipStatus: false,
    notes: [],
  },
  {
    id: "gst_022",
    fullName: "Efua Mensah",
    phone: "+233 27 222 3344",
    email: "efua.mensah@email.com",
    nationality: "Ghanaian",
    idType: "national_id",
    idNumber: "GHA-778899001-7",
    address: "Labadi, Accra",
    guestStatus: "reserved",
    totalVisits: 2,
    totalSpent: 1400,
    vipStatus: false,
    notes: ["Requires airport pickup"],
  },
  {
    id: "gst_023",
    fullName: "Isabella Rossi",
    phone: "+39 333 1234567",
    email: "isabella.r@email.it",
    nationality: "Italian",
    idType: "passport",
    idNumber: "IT556677",
    address: "Rome, Italy",
    guestStatus: "checked_out",
    totalVisits: 1,
    totalSpent: 890,
    vipStatus: false,
    notes: [],
  },
  {
    id: "gst_024",
    fullName: "Samuel Tetteh",
    phone: "+233 24 666 7788",
    email: "samuel.tetteh@email.com",
    nationality: "Ghanaian",
    idType: "national_id",
    idNumber: "GHA-889900112-8",
    address: "Madina, Accra",
    guestStatus: "in_house",
    totalVisits: 5,
    totalSpent: 7200,
    vipStatus: true,
    notes: ["Corporate rate", "Returning guest"],
  },
  {
    id: "gst_025",
    fullName: "Mei Lin",
    phone: "+86 138 0013 8000",
    email: "mei.lin@email.cn",
    nationality: "Chinese",
    idType: "passport",
    idNumber: "CN99887766",
    address: "Shanghai, China",
    guestStatus: "reserved",
    totalVisits: 1,
    totalSpent: 0,
    vipStatus: false,
    notes: ["Mandarin-speaking staff preferred"],
  },
];

export function getGuestById(id: string): Guest | undefined {
  return mockGuests.find((g) => g.id === id);
}

export function findGuestByEmail(email: string): Guest | undefined {
  return mockGuests.find(
    (g) => g.email.toLowerCase() === email.toLowerCase()
  );
}

export function computeGuestStats(guests: Guest[]): GuestStats {
  return {
    totalGuests: guests.length,
    currentGuests: guests.filter((g) => g.guestStatus === "in_house").length,
    returningGuests: guests.filter((g) => g.totalVisits > 1).length,
    vipGuests: guests.filter((g) => g.vipStatus).length,
    checkInsToday: guests.filter((g) => g.guestStatus === "in_house").length,
    checkOutsToday: 2,
  };
}

export const mockGuestStats = computeGuestStats(mockGuests);
