import type { Notification } from "@/types/notification";

export const mockNotifications: Notification[] = [
  {
    id: "ntf_001",
    title: "New Reservation",
    message: "SHMS-2026-0142 — Kwame Mensah arriving Jun 5",
    type: "new_reservation",
    priority: "medium",
    read: false,
    createdAt: "2026-06-02T10:45:00",
    module: "Reservations",
  },
  {
    id: "ntf_002",
    title: "Payment Received",
    message: "GH₵ 1,200.00 deposit from Kwame Mensah",
    type: "payment_received",
    priority: "low",
    read: false,
    createdAt: "2026-06-02T10:02:00",
    module: "Payments",
  },
  {
    id: "ntf_003",
    title: "Guest Checked In",
    message: "Ama Osei checked into Room 003",
    type: "guest_checked_in",
    priority: "medium",
    read: false,
    createdAt: "2026-06-02T09:15:00",
    module: "Check-In",
  },
  {
    id: "ntf_004",
    title: "Outstanding Balance Alert",
    message: "James Okonkwo — GH₵ 2,415.00 balance on res_003",
    type: "outstanding_balance",
    priority: "critical",
    read: false,
    createdAt: "2026-06-02T08:00:00",
    module: "Payments",
  },
  {
    id: "ntf_005",
    title: "Room Ready",
    message: "Room 014 inspected and ready for guest",
    type: "room_ready",
    priority: "low",
    read: true,
    createdAt: "2026-06-01T16:30:00",
    module: "Housekeeping",
  },
  {
    id: "ntf_006",
    title: "Housekeeping Task Assigned",
    message: "Room 006 assigned to Kofi Annan",
    type: "housekeeping_assigned",
    priority: "medium",
    read: true,
    createdAt: "2026-06-01T14:00:00",
    module: "Housekeeping",
  },
  {
    id: "ntf_007",
    title: "Guest Checked Out",
    message: "Michael Chen departed from Room 015",
    type: "guest_checked_out",
    priority: "low",
    read: true,
    createdAt: "2026-06-01T11:00:00",
    module: "Check-Out",
  },
  {
    id: "ntf_008",
    title: "Payment Received",
    message: "GH₵ 2,760.00 from Fatima Al-Rashid",
    type: "payment_received",
    priority: "low",
    read: true,
    createdAt: "2026-06-01T10:00:00",
    module: "Payments",
  },
];

export const unreadNotifications = mockNotifications.filter((n) => !n.read);
export const readNotifications = mockNotifications.filter((n) => n.read);
