/**
 * Ordered migration files — must match supabase/migrations/
 * Apply via: supabase db push / supabase migration up
 */
export const MIGRATION_ORDER = [
  "000_extensions.sql",
  "001_roles.sql",
  "002_permissions.sql",
  "003_role_permissions.sql",
  "004_users.sql",
  "005_staff_profiles.sql",
  "006_room_types.sql",
  "007_rooms.sql",
  "008_guests.sql",
  "009_reservations.sql",
  "010_reservation_guests.sql",
  "011_payments.sql",
  "012_invoices.sql",
  "013_housekeeping_tasks.sql",
  "014_notifications.sql",
  "015_activity_logs.sql",
  "016_hotel_settings.sql",
  "017_rls_enable.sql",
  "018_public_booking_requests.sql",
  "019_rls_public_booking_requests.sql",
  "020_auth_helpers.sql",
  "021_users_must_change_password.sql",
  "022_staff_avatars_storage.sql",
  "023_roles_permission_module.sql",
  "024_roles_permission_grants.sql",
  "025_production_hardening.sql",
  "026_users_last_login_rls.sql",
  "027_payment_method_mixed.sql",
  "028_transaction_receipts.sql",
  "029_night_audit.sql",
  "030_floors_master.sql",
  "031_floors_permission_module.sql",
  "032_floors_permission_grants.sql",
  "033_night_audit_permission_module.sql",
  "034_night_audit_permission_grants.sql",
  "035_night_audit_numbers.sql",
  "036_cash_variance.sql",
  "037_shift_handover.sql",
  "038_shift_handover_permission_module.sql",
  "039_shift_handover_permission_grants.sql",
  "040_early_checkout.sql",
  "041_late_checkout.sql",
  "042_late_checkout_policy.sql",
  "043_extend_stay_room_move.sql",
  "044_profile_branding.sql",
  "045_room_photos.sql",
] as const;

export const SEED_ORDER = [
  "001_permissions.sql",
  "002_role_permissions.sql",
  "003_room_types.sql",
  "004_rooms.sql",
  "005_hotel_settings.sql",
] as const;
