export type PaperSize = "a4" | "thermal_80mm" | "thermal_58mm";
export type PrinterMode = "browser" | "silent";

export type HotelSettings = {
  hotelName: string;
  address: string;
  phone: string;
  email: string;
  website: string;
  tinNumber: string;
  registrationNumber: string;
  description: string;
  primaryColor: string;
  secondaryColor: string;
  theme: "light" | "dark" | "system";
  logoUrl: string;
  faviconUrl: string;
  checkInTime: string;
  checkOutTime: string;
  lateCheckoutFee: number;
  lateCheckoutPolicyMode: "flat" | "hour_based";
  lateCheckoutHourFee1To2: number;
  lateCheckoutHourFee2To4: number;
  lateCheckoutHourFee4To6: number;
  currency: string;
  currencySymbol: string;
  currencyPosition: "before" | "after";
  timeZone: string;
  taxRate: number;
  serviceCharge: number;
  invoicePrefix: string;
  invoiceStartingNumber: number;
  invoiceDueDays: number;
  autoGenerateInvoiceNumber: boolean;
  receiptPrefix: string;
  receiptStartingNumber: number;
  receiptHeaderMessage: string;
  receiptFooterMessage: string;
  showHotelLogo: boolean;
  showQrCode: boolean;
  printThankYouMessage: boolean;
  invoiceFooter: string;
  termsAndConditions: string;
  paperSize: PaperSize;
  defaultPrinterMode: PrinterMode;
  autoPrintAfterPayment: boolean;
  askBeforePrinting: boolean;
  reservationEmailTemplate: string;
  invoiceEmailTemplate: string;
  reminderEmailTemplate: string;
  emailNotifications: boolean;
  smsNotifications: boolean;
  paymentAlerts: boolean;
  reservationAlerts: boolean;
  housekeepingAlerts: boolean;
};
