export type HotelSettings = {
  hotelName: string;
  address: string;
  phone: string;
  email: string;
  website: string;
  tinNumber: string;
  description: string;
  primaryColor: string;
  secondaryColor: string;
  theme: "light" | "dark" | "system";
  logoUrl: string;
  faviconUrl: string;
  checkInTime: string;
  checkOutTime: string;
  lateCheckoutFee: number;
  lateCheckoutPolicyMode: "flat" | "hour_based";
  lateCheckoutHourFee1To2: number;
  lateCheckoutHourFee2To4: number;
  lateCheckoutHourFee4To6: number;
  currency: string;
  timeZone: string;
  taxRate: number;
  serviceCharge: number;
  invoicePrefix: string;
  receiptPrefix: string;
  invoiceFooter: string;
  termsAndConditions: string;
  reservationEmailTemplate: string;
  invoiceEmailTemplate: string;
  reminderEmailTemplate: string;
  emailNotifications: boolean;
  smsNotifications: boolean;
  paymentAlerts: boolean;
  reservationAlerts: boolean;
  housekeepingAlerts: boolean;
};
